# ansible-playbook -i inventory agent.yaml -u centos --key-file=node.pem -b
---
- hosts: agents
  become: yes
  #become_user: root
  gather_facts: true
  tasks:
    - name: disable SELinux
      selinux:
        state: disabled
      when:
        ansible_os_family == "RedHat"

    #- name: install pcre2
    #  yum:
    #    name: "pcre2-devel.x86_64"

    - name: install zabbix centOS 7 rpm file
      yum:
        name: "https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-release-6.2-3.el7.noarch.rpm"
        validate_certs: no
      when:
        ansible_os_family == "RedHat"

    - name: update all packages
      yum: name=* state=latest
      when:
        ansible_os_family == "RedHat"

    - name: install zabbix-agent 6.x for centOS 7
      yum: 
        name: zabbix-agent
        state: latest
      when:
        ansible_os_family == "RedHat"
      notify:
        zabbix-agent systemd

    - name: Copy zabbix_agentd.conf file with owner and permissions
      ansible.builtin.copy:
        src: /etc/ansible/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
      when:
        ansible_os_family == "RedHat"


    - name: Download zabbix-agent
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu20.04_all.deb
        dest: /home/ansible-admin/zabbix-release_6.2-4+ubuntu20.04_all.deb
        mode: '0777'
      when:
          ansible_os_family == "Debian"

    - name: install a .deb package
      ansible.builtin.apt:
        deb: /home/ansible-admin/zabbix-release_6.2-4+ubuntu20.04_all.deb
      when:
        ansible_os_family == "Debian"

    - name: Update all packkages
      ansible.builtin.apt:
        name: "*"
        state: latest
      when:
        ansible_os_family == "Debian"


    - name: Install zabbix-agent2 Ubuntu
      ansible.builtin.apt:
        name: '{{ item }}'
        update_cache: yes
      with_items:
              - zabbix-agent2
              - zabbix-agent2-plugin-*
      when:
        ansible_os_family == "Debian"
      notify:
        zabbix-agent2 systemd


    - name: Copy zabbix_agent2.conf file with owner and permissions
      ansible.builtin.copy:
        src: /etc/ansible/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf
      when:
        ansible_os_family == "Debian"
  
  
  handlers:
    - name: zabbix-agent systemd
      ansible.builtin.service:
        name: zabbix-agent
        enabled: yes
        state: started
    - name: zabbix-agent2 systemd
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: yes
        state: started     
